### ISSUE TITLE
Can't add a region with the DumpingGeoJSONs.py

### ISSUE THREAD

**Issue by Anaraquelpengelly** [lc5415/COVIDTracker#8]
after pasting the json, that looks like this : 
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -15.1171875,
              33.7243396617476
            ],
            [
              32.51953125,
              33.7243396617476
            ],
            [
              32.51953125,
              61.64816245852389
            ],
            [
              -15.1171875,
              61.64816245852389
            ],
            [
              -15.1171875,
              33.7243396617476
            ]
          ]
        ]
      }
    }
  ]
I get this: 
<img width="343" alt="Screenshot 2020-04-07 at 18 50 36" src="https://user-images.githubusercontent.com/23666946/78702585-b90fc200-7900-11ea-8afc-a774d2c3d608.png">
Maybe I am doing something wrong?

**Comment by Anaraquelpengelly** [comment]
on a different subject, the BatchStreamListener.py doesn't let me do a search without location, is that normal?

**Comment by lc5415** [comment]
Ana I've just fixed this issue, I am gonna have a quick look at the BatchStreamListener now
